services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
    networks:
      - url_shortener_server

  url_shortener_db:
    image: postgres:13-alpine
    container_name: url_shortener_db 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Bangkok
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - url_shortener_server
  app:
    build: .
    depends_on:
      - url_shortener_db
      - dragonfly
    restart: always
    ports:
      - "8080:8080"
    environment:
      APP_ENV: development
      DB_HOST: url_shortener_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
    networks:
      - url_shortener_server
volumes:
  postgres_data:
  dragonflydata:
networks:
  url_shortener_server:
