// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: generate.sql

package db

import (
	"context"
	"time"
)

const checkShortUrlExists = `-- name: CheckShortUrlExists :one
SELECT EXISTS (
    SELECT 1 FROM urls
    WHERE short_url = $1
)
`

func (q *Queries) CheckShortUrlExists(ctx context.Context, shortUrl string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkShortUrlExists, shortUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteExpiredShortUrl = `-- name: DeleteExpiredShortUrl :exec
DELETE FROM urls WHERE short_url = $1
`

func (q *Queries) DeleteExpiredShortUrl(ctx context.Context, shortUrl string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredShortUrl, shortUrl)
	return err
}

const insertNewShortUrl = `-- name: InsertNewShortUrl :one
INSERT INTO urls (original_url, short_url, expired_at) VALUES ( $1, $2, $3) RETURNING id, original_url, short_url, created_at, expired_at
`

type InsertNewShortUrlParams struct {
	OriginalUrl string
	ShortUrl    string
	ExpiredAt   time.Time
}

func (q *Queries) InsertNewShortUrl(ctx context.Context, arg InsertNewShortUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, insertNewShortUrl, arg.OriginalUrl, arg.ShortUrl, arg.ExpiredAt)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const retrieveShortUrl = `-- name: RetrieveShortUrl :one
SELECT id, original_url, short_url, created_at, expired_at FROM urls
WHERE short_url = $1 LIMIT 1
`

func (q *Queries) RetrieveShortUrl(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, retrieveShortUrl, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
