// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Url struct {
	ID          int64
	OriginalUrl string
	ShortUrl    string
	CreatedAt   sql.NullTime
	ExpiredAt   time.Time
}
